// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/asaberwd/atomica-blog/swagger/restapi/operations/comment"
	"github.com/asaberwd/atomica-blog/swagger/restapi/operations/comments"
	"github.com/asaberwd/atomica-blog/swagger/restapi/operations/doc"
	"github.com/asaberwd/atomica-blog/swagger/restapi/operations/health_api"
	"github.com/asaberwd/atomica-blog/swagger/restapi/operations/post"
)

// NewAtomicaBlogServiceAPI creates a new AtomicaBlogService instance
func NewAtomicaBlogServiceAPI(spec *loads.Document) *AtomicaBlogServiceAPI {
	return &AtomicaBlogServiceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		HTMLProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("html producer has not yet been implemented")
		}),
		PostAddPostHandler: post.AddPostHandlerFunc(func(params post.AddPostParams) middleware.Responder {
			return middleware.NotImplemented("operation PostAddPost has not yet been implemented")
		}),
		CommentsAddPostCommentHandler: comments.AddPostCommentHandlerFunc(func(params comments.AddPostCommentParams) middleware.Responder {
			return middleware.NotImplemented("operation CommentsAddPostComment has not yet been implemented")
		}),
		PostDeletePostHandler: post.DeletePostHandlerFunc(func(params post.DeletePostParams) middleware.Responder {
			return middleware.NotImplemented("operation PostDeletePost has not yet been implemented")
		}),
		DocGetDocHandler: doc.GetDocHandlerFunc(func(params doc.GetDocParams) middleware.Responder {
			return middleware.NotImplemented("operation DocGetDoc has not yet been implemented")
		}),
		PostGetPostByIDHandler: post.GetPostByIDHandlerFunc(func(params post.GetPostByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PostGetPostByID has not yet been implemented")
		}),
		CommentsGetPostCommentsByIDHandler: comments.GetPostCommentsByIDHandlerFunc(func(params comments.GetPostCommentsByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation CommentsGetPostCommentsByID has not yet been implemented")
		}),
		PostGetPostsHandler: post.GetPostsHandlerFunc(func(params post.GetPostsParams) middleware.Responder {
			return middleware.NotImplemented("operation PostGetPosts has not yet been implemented")
		}),
		HealthAPIHealthCheckHandler: health_api.HealthCheckHandlerFunc(func(params health_api.HealthCheckParams) middleware.Responder {
			return middleware.NotImplemented("operation HealthAPIHealthCheck has not yet been implemented")
		}),
		PostUpdatePostHandler: post.UpdatePostHandlerFunc(func(params post.UpdatePostParams) middleware.Responder {
			return middleware.NotImplemented("operation PostUpdatePost has not yet been implemented")
		}),
		CommentUpdatePostCommentHandler: comment.UpdatePostCommentHandlerFunc(func(params comment.UpdatePostCommentParams) middleware.Responder {
			return middleware.NotImplemented("operation CommentUpdatePostComment has not yet been implemented")
		}),
	}
}

/*AtomicaBlogServiceAPI the atomica blog service API */
type AtomicaBlogServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer
	// HTMLProducer registers a producer for a "text/html" mime type
	HTMLProducer runtime.Producer

	// PostAddPostHandler sets the operation handler for the add post operation
	PostAddPostHandler post.AddPostHandler
	// CommentsAddPostCommentHandler sets the operation handler for the add post comment operation
	CommentsAddPostCommentHandler comments.AddPostCommentHandler
	// PostDeletePostHandler sets the operation handler for the delete post operation
	PostDeletePostHandler post.DeletePostHandler
	// DocGetDocHandler sets the operation handler for the get doc operation
	DocGetDocHandler doc.GetDocHandler
	// PostGetPostByIDHandler sets the operation handler for the get post by Id operation
	PostGetPostByIDHandler post.GetPostByIDHandler
	// CommentsGetPostCommentsByIDHandler sets the operation handler for the get post comments by Id operation
	CommentsGetPostCommentsByIDHandler comments.GetPostCommentsByIDHandler
	// PostGetPostsHandler sets the operation handler for the get posts operation
	PostGetPostsHandler post.GetPostsHandler
	// HealthAPIHealthCheckHandler sets the operation handler for the health check operation
	HealthAPIHealthCheckHandler health_api.HealthCheckHandler
	// PostUpdatePostHandler sets the operation handler for the update post operation
	PostUpdatePostHandler post.UpdatePostHandler
	// CommentUpdatePostCommentHandler sets the operation handler for the update post comment operation
	CommentUpdatePostCommentHandler comment.UpdatePostCommentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *AtomicaBlogServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *AtomicaBlogServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *AtomicaBlogServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *AtomicaBlogServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *AtomicaBlogServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *AtomicaBlogServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *AtomicaBlogServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the AtomicaBlogServiceAPI
func (o *AtomicaBlogServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.HTMLProducer == nil {
		unregistered = append(unregistered, "HTMLProducer")
	}

	if o.PostAddPostHandler == nil {
		unregistered = append(unregistered, "post.AddPostHandler")
	}

	if o.CommentsAddPostCommentHandler == nil {
		unregistered = append(unregistered, "comments.AddPostCommentHandler")
	}

	if o.PostDeletePostHandler == nil {
		unregistered = append(unregistered, "post.DeletePostHandler")
	}

	if o.DocGetDocHandler == nil {
		unregistered = append(unregistered, "doc.GetDocHandler")
	}

	if o.PostGetPostByIDHandler == nil {
		unregistered = append(unregistered, "post.GetPostByIDHandler")
	}

	if o.CommentsGetPostCommentsByIDHandler == nil {
		unregistered = append(unregistered, "comments.GetPostCommentsByIDHandler")
	}

	if o.PostGetPostsHandler == nil {
		unregistered = append(unregistered, "post.GetPostsHandler")
	}

	if o.HealthAPIHealthCheckHandler == nil {
		unregistered = append(unregistered, "health_api.HealthCheckHandler")
	}

	if o.PostUpdatePostHandler == nil {
		unregistered = append(unregistered, "post.UpdatePostHandler")
	}

	if o.CommentUpdatePostCommentHandler == nil {
		unregistered = append(unregistered, "comment.UpdatePostCommentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *AtomicaBlogServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *AtomicaBlogServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *AtomicaBlogServiceAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *AtomicaBlogServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *AtomicaBlogServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		case "text/html":
			result["text/html"] = o.HTMLProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *AtomicaBlogServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the atomica blog service API
func (o *AtomicaBlogServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *AtomicaBlogServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/posts"] = post.NewAddPost(o.context, o.PostAddPostHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/post/{postId}/comments"] = comments.NewAddPostComment(o.context, o.CommentsAddPostCommentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/post/{postId}"] = post.NewDeletePost(o.context, o.PostDeletePostHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api-docs"] = doc.NewGetDoc(o.context, o.DocGetDocHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/post/{postId}"] = post.NewGetPostByID(o.context, o.PostGetPostByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/post/{postId}/comments"] = comments.NewGetPostCommentsByID(o.context, o.CommentsGetPostCommentsByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts"] = post.NewGetPosts(o.context, o.PostGetPostsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = health_api.NewHealthCheck(o.context, o.HealthAPIHealthCheckHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/post/{postId}"] = post.NewUpdatePost(o.context, o.PostUpdatePostHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/post/{postId}/comment/{commentId}"] = comment.NewUpdatePostComment(o.context, o.CommentUpdatePostCommentHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *AtomicaBlogServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *AtomicaBlogServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *AtomicaBlogServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *AtomicaBlogServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
