// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindPostsByTagsHandlerFunc turns a function with the right signature into a find posts by tags handler
type FindPostsByTagsHandlerFunc func(FindPostsByTagsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn FindPostsByTagsHandlerFunc) Handle(params FindPostsByTagsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// FindPostsByTagsHandler interface for that can handle valid find posts by tags params
type FindPostsByTagsHandler interface {
	Handle(FindPostsByTagsParams, interface{}) middleware.Responder
}

// NewFindPostsByTags creates a new http.Handler for the find posts by tags operation
func NewFindPostsByTags(ctx *middleware.Context, handler FindPostsByTagsHandler) *FindPostsByTags {
	return &FindPostsByTags{Context: ctx, Handler: handler}
}

/* FindPostsByTags swagger:route GET /post/findByTags post findPostsByTags

Finds Posts by tags

Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.

*/
type FindPostsByTags struct {
	Context *middleware.Context
	Handler FindPostsByTagsHandler
}

func (o *FindPostsByTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindPostsByTagsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
