// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPostByIDHandlerFunc turns a function with the right signature into a get post by Id handler
type GetPostByIDHandlerFunc func(GetPostByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPostByIDHandlerFunc) Handle(params GetPostByIDParams) middleware.Responder {
	return fn(params)
}

// GetPostByIDHandler interface for that can handle valid get post by Id params
type GetPostByIDHandler interface {
	Handle(GetPostByIDParams) middleware.Responder
}

// NewGetPostByID creates a new http.Handler for the get post by Id operation
func NewGetPostByID(ctx *middleware.Context, handler GetPostByIDHandler) *GetPostByID {
	return &GetPostByID{Context: ctx, Handler: handler}
}

/*GetPostByID swagger:route GET /post/{postId} post getPostById

Get post by ID

Returns a single post by its id

*/
type GetPostByID struct {
	Context *middleware.Context
	Handler GetPostByIDHandler
}

func (o *GetPostByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPostByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
