// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/asaberwd/atomica-blog/swagger/models"
)

// GetPostsOKCode is the HTTP code returned for type GetPostsOK
const GetPostsOKCode int = 200

/*GetPostsOK successful operation

swagger:response getPostsOK
*/
type GetPostsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Posts `json:"body,omitempty"`
}

// NewGetPostsOK creates GetPostsOK with default headers values
func NewGetPostsOK() *GetPostsOK {

	return &GetPostsOK{}
}

// WithPayload adds the payload to the get posts o k response
func (o *GetPostsOK) WithPayload(payload *models.Posts) *GetPostsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts o k response
func (o *GetPostsOK) SetPayload(payload *models.Posts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsBadRequestCode is the HTTP code returned for type GetPostsBadRequest
const GetPostsBadRequestCode int = 400

/*GetPostsBadRequest Invalid request

swagger:response getPostsBadRequest
*/
type GetPostsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPostsBadRequest creates GetPostsBadRequest with default headers values
func NewGetPostsBadRequest() *GetPostsBadRequest {

	return &GetPostsBadRequest{}
}

// WithPayload adds the payload to the get posts bad request response
func (o *GetPostsBadRequest) WithPayload(payload *models.Error) *GetPostsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts bad request response
func (o *GetPostsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPostsNotFoundCode is the HTTP code returned for type GetPostsNotFound
const GetPostsNotFoundCode int = 404

/*GetPostsNotFound Not found.

swagger:response getPostsNotFound
*/
type GetPostsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPostsNotFound creates GetPostsNotFound with default headers values
func NewGetPostsNotFound() *GetPostsNotFound {

	return &GetPostsNotFound{}
}

// WithPayload adds the payload to the get posts not found response
func (o *GetPostsNotFound) WithPayload(payload *models.Error) *GetPostsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts not found response
func (o *GetPostsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
