// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePostWithFormMethodNotAllowedCode is the HTTP code returned for type UpdatePostWithFormMethodNotAllowed
const UpdatePostWithFormMethodNotAllowedCode int = 405

/*UpdatePostWithFormMethodNotAllowed Invalid input

swagger:response updatePostWithFormMethodNotAllowed
*/
type UpdatePostWithFormMethodNotAllowed struct {
}

// NewUpdatePostWithFormMethodNotAllowed creates UpdatePostWithFormMethodNotAllowed with default headers values
func NewUpdatePostWithFormMethodNotAllowed() *UpdatePostWithFormMethodNotAllowed {

	return &UpdatePostWithFormMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePostWithFormMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
