// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePostBadRequestCode is the HTTP code returned for type UpdatePostBadRequest
const UpdatePostBadRequestCode int = 400

/*UpdatePostBadRequest Invalid ID supplied

swagger:response updatePostBadRequest
*/
type UpdatePostBadRequest struct {
}

// NewUpdatePostBadRequest creates UpdatePostBadRequest with default headers values
func NewUpdatePostBadRequest() *UpdatePostBadRequest {

	return &UpdatePostBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePostNotFoundCode is the HTTP code returned for type UpdatePostNotFound
const UpdatePostNotFoundCode int = 404

/*UpdatePostNotFound Post not found

swagger:response updatePostNotFound
*/
type UpdatePostNotFound struct {
}

// NewUpdatePostNotFound creates UpdatePostNotFound with default headers values
func NewUpdatePostNotFound() *UpdatePostNotFound {

	return &UpdatePostNotFound{}
}

// WriteResponse to the client
func (o *UpdatePostNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdatePostMethodNotAllowedCode is the HTTP code returned for type UpdatePostMethodNotAllowed
const UpdatePostMethodNotAllowedCode int = 405

/*UpdatePostMethodNotAllowed Validation exception

swagger:response updatePostMethodNotAllowed
*/
type UpdatePostMethodNotAllowed struct {
}

// NewUpdatePostMethodNotAllowed creates UpdatePostMethodNotAllowed with default headers values
func NewUpdatePostMethodNotAllowed() *UpdatePostMethodNotAllowed {

	return &UpdatePostMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePostMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
