// Code generated by go-swagger; DO NOT EDIT.

package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdatePostWithFormHandlerFunc turns a function with the right signature into a update post with form handler
type UpdatePostWithFormHandlerFunc func(UpdatePostWithFormParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePostWithFormHandlerFunc) Handle(params UpdatePostWithFormParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdatePostWithFormHandler interface for that can handle valid update post with form params
type UpdatePostWithFormHandler interface {
	Handle(UpdatePostWithFormParams, interface{}) middleware.Responder
}

// NewUpdatePostWithForm creates a new http.Handler for the update post with form operation
func NewUpdatePostWithForm(ctx *middleware.Context, handler UpdatePostWithFormHandler) *UpdatePostWithForm {
	return &UpdatePostWithForm{Context: ctx, Handler: handler}
}

/* UpdatePostWithForm swagger:route POST /post/{postId} post updatePostWithForm

Updates a post in the blog with form data

*/
type UpdatePostWithForm struct {
	Context *middleware.Context
	Handler UpdatePostWithFormHandler
}

func (o *UpdatePostWithForm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdatePostWithFormParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
