service: atomica-blog

frameworkVersion: '2'

variablesResolutionMode: 20210326
configValidationMode: error

plugins:
  - serverless-localstack
  - serverless-plugin-tracing
  - serverless-prune-plugin
  - serverless-pseudo-parameters
  - serverless-plugin-datadog
custom:
  stage: ${opt:stage, 'dev'}
  pgconn: ${ssm:/atomica/postgresql/${self:custom.stage}}
  localstack:
    debug: true
    stages:
      - local
  prune:
    automatic: true
    number: 3
  datadog:
    site: datadoghq.com
    apiKey: 316968bdd464409bce866828005abe2f


package:
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: 'Allow'
      Action:
        - 'ecs:*'
        - "iam:GetRole"
        - "iam:PassRole"
      Resource: '*'

  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}

  environment:
    stage: ${self:provider.stage}
    region: ${self:provider.region}

functions:
  atomicaBlogApi:
    name: ${self:service}-v1-api
    timeout: 10
    handler: bin/atomica-blog-api
    runtime: go1.x
    memorySize: 512
    environment:
      PGCONN: ${self:custom.pgconn}
      STAGE: ${self:custom.stage}

    events:
      - http:
          path: v1/{any+}
          method: any
