// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Atomica Blogspot

    Schemes:
      http
      https
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/html

swagger:meta
*/
package restapi
