// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePostCommentBadRequestCode is the HTTP code returned for type UpdatePostCommentBadRequest
const UpdatePostCommentBadRequestCode int = 400

/*UpdatePostCommentBadRequest Invalid ID supplied

swagger:response updatePostCommentBadRequest
*/
type UpdatePostCommentBadRequest struct {
}

// NewUpdatePostCommentBadRequest creates UpdatePostCommentBadRequest with default headers values
func NewUpdatePostCommentBadRequest() *UpdatePostCommentBadRequest {

	return &UpdatePostCommentBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePostCommentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePostCommentNotFoundCode is the HTTP code returned for type UpdatePostCommentNotFound
const UpdatePostCommentNotFoundCode int = 404

/*UpdatePostCommentNotFound Post not found

swagger:response updatePostCommentNotFound
*/
type UpdatePostCommentNotFound struct {
}

// NewUpdatePostCommentNotFound creates UpdatePostCommentNotFound with default headers values
func NewUpdatePostCommentNotFound() *UpdatePostCommentNotFound {

	return &UpdatePostCommentNotFound{}
}

// WriteResponse to the client
func (o *UpdatePostCommentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdatePostCommentMethodNotAllowedCode is the HTTP code returned for type UpdatePostCommentMethodNotAllowed
const UpdatePostCommentMethodNotAllowedCode int = 405

/*UpdatePostCommentMethodNotAllowed Validation exception

swagger:response updatePostCommentMethodNotAllowed
*/
type UpdatePostCommentMethodNotAllowed struct {
}

// NewUpdatePostCommentMethodNotAllowed creates UpdatePostCommentMethodNotAllowed with default headers values
func NewUpdatePostCommentMethodNotAllowed() *UpdatePostCommentMethodNotAllowed {

	return &UpdatePostCommentMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePostCommentMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
