// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// UpdatePostCommentURL generates an URL for the update post comment operation
type UpdatePostCommentURL struct {
	CommentID int64
	PostID    int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdatePostCommentURL) WithBasePath(bp string) *UpdatePostCommentURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdatePostCommentURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdatePostCommentURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/post/{postId}/comment/{commentId}"

	commentID := swag.FormatInt64(o.CommentID)
	if commentID != "" {
		_path = strings.Replace(_path, "{commentId}", commentID, -1)
	} else {
		return nil, errors.New("commentId is required on UpdatePostCommentURL")
	}

	postID := swag.FormatInt64(o.PostID)
	if postID != "" {
		_path = strings.Replace(_path, "{postId}", postID, -1)
	} else {
		return nil, errors.New("postId is required on UpdatePostCommentURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdatePostCommentURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdatePostCommentURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdatePostCommentURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdatePostCommentURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdatePostCommentURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdatePostCommentURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
