// Code generated by go-swagger; DO NOT EDIT.

package comment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdatePostCommentHandlerFunc turns a function with the right signature into a update post comment handler
type UpdatePostCommentHandlerFunc func(UpdatePostCommentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePostCommentHandlerFunc) Handle(params UpdatePostCommentParams) middleware.Responder {
	return fn(params)
}

// UpdatePostCommentHandler interface for that can handle valid update post comment params
type UpdatePostCommentHandler interface {
	Handle(UpdatePostCommentParams) middleware.Responder
}

// NewUpdatePostComment creates a new http.Handler for the update post comment operation
func NewUpdatePostComment(ctx *middleware.Context, handler UpdatePostCommentHandler) *UpdatePostComment {
	return &UpdatePostComment{Context: ctx, Handler: handler}
}

/*UpdatePostComment swagger:route PUT /post/{postId}/comment/{commentId} comment updatePostComment

Update an existing comment

*/
type UpdatePostComment struct {
	Context *middleware.Context
	Handler UpdatePostCommentHandler
}

func (o *UpdatePostComment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdatePostCommentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
