// Code generated by go-swagger; DO NOT EDIT.

package doc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDocHandlerFunc turns a function with the right signature into a get doc handler
type GetDocHandlerFunc func(GetDocParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDocHandlerFunc) Handle(params GetDocParams) middleware.Responder {
	return fn(params)
}

// GetDocHandler interface for that can handle valid get doc params
type GetDocHandler interface {
	Handle(GetDocParams) middleware.Responder
}

// NewGetDoc creates a new http.Handler for the get doc operation
func NewGetDoc(ctx *middleware.Context, handler GetDocHandler) *GetDoc {
	return &GetDoc{Context: ctx, Handler: handler}
}

/*GetDoc swagger:route GET /api-docs doc getDoc

Get swagger documentation

*/
type GetDoc struct {
	Context *middleware.Context
	Handler GetDocHandler
}

func (o *GetDoc) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDocParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
