// Code generated by go-swagger; DO NOT EDIT.

package doc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDocOKCode is the HTTP code returned for type GetDocOK
const GetDocOKCode int = 200

/*GetDocOK Success

swagger:response getDocOK
*/
type GetDocOK struct {
}

// NewGetDocOK creates GetDocOK with default headers values
func NewGetDocOK() *GetDocOK {

	return &GetDocOK{}
}

// WriteResponse to the client
func (o *GetDocOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
